### ISSUE TITLE
Big Sure new installation stuck on about 30 sec of OS booting

### ISSUE THREAD

**Issue by adrianzhang** [wouterds/hackintosh#1]
It is so glad to find a z170n-wifi EFI, thank you very much!

I have same MB(same rev1.0), and i5-6500, 2xDDR4 2400 16GB，512GB Nvme SSD (Micron P2), Graphic card is XFX RX560, and also a DW1560 wifi card :)

Problem:

I'v already installed Clover+Catalina 10.13.4 (on Fusion drive 256GB Toshiba SATA+2TB WD 5400rpm) half year ago. And leave it shutdown for 3 months. Once I came back and want to use it, it could not boot the OS (Clover was fine).
[hardware is same except HD and without Graphic card]

So I changed hardware as described in the begging in order to fresh install Big Sure.

I'v downloaded Big Sure .4 version, made install flash disk with this image and your EFI. Everything is fine until booting OS several seconds it stuck and show me a forbidden apple icon.

I have no clue what happened caused Catalina and Big Sure not booting, I've tried adjust BIOS but nothing helped. 

Could you please share BIOS configuration? And, do you have any advise to troubleshoot?

Thank you in advance,

Regards,

Adrian

**Comment by adrianzhang** [comment]
I find another EFI from https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/
This EFI makes iTX machine boot into the interface that show me 4 options which last one is Disk Utility, but USB mouse is no responding. I am working on it.

**Comment by adrianzhang** [comment]
> I find another EFI from https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/
> This EFI makes iTX machine boot into the interface that show me 4 options which last one is Disk Utility, but USB mouse is no responding. I am working on it.

Fixed USB problem with disable XhciPortLimit.

**Comment by adrianzhang** [comment]
Update: 

After boot Big Sur with that EFI, Bluetooth works well but no wifi card found, Looks like more work to do with kexts. 
And, good news is that I find some topics about Catalina update, which say Lilu and WhateverGreen should be updated first, so I update both in EFI on old Fusion drive, guess what, old Catalina boot up, (although USB don't work). 
Anyway I know what cause Catalina problem, it should be an update before I shutdown it! Damm.

So the situation right now:
1) I have a working Catalina without USB devices.
2) Your Big Sur EFI can not boot machine.
3) Another EFI with a little bit change of USB config can boot machine, without wifi function.
2 and 3 situations means that your EFI has some problems.

> > I find another EFI from https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/
> > This EFI makes iTX machine boot into the interface that show me 4 options which last one is Disk Utility, but USB mouse is no responding. I am working on it.
> 
> Fixed USB problem with disable XhciPortLimit.

**Comment by 13372208606** [comment]
> 更新：
> 
> 使用该 EFI 启动 Big Sur 后，蓝牙工作正常，但找不到 wifi 卡，看起来与 kexts 相关的工作更多。
> 而且，好消息是我发现了一些关于 Catalina 更新的主题，其中说 Lilu 和 WhatGreen 应该先更新，所以我在旧 Fusion 驱动器上的 EFI 中更新了两者，猜猜看，旧的 Catalina 启动，（虽然 USB 不起作用）。
> 无论如何我知道是什么导致了 Catalina 问题，它应该是我关闭它之前的更新！妈的。
> 
> 所以现在的情况：
> 
> 1. 我有一个没有 USB 设备的工作 Catalina。
> 2. 您的 Big Sur EFI 无法启动机器。
> 3. 另一个稍微改变USB配置的EFI可以启动机器，没有wifi功能。
>    2、3种情况说明你的EFI有问题。
> 
> > > 我从https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/找到另一个 EFI [/](https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/)
> > > 这个 EFI 使 iTX 机器启动到显示我 4 个选项的界面，最后一个是磁盘实用程序，但 USB 鼠标没有响应。我正在做。
> > 
> > 
> > 修复了禁用 XhciPortLimit 的 USB 问题。

Can you share it     mailbox 1172036926@qq.com

**Comment by 13372208606** [comment]
> > 更新：
> > 使用该 EFI 启动 Big Sur 后，蓝牙工作正常，但找不到 wifi 卡，与 kexts 相关的更多。
> > 而且，好消息是我发现了一些关于 Catalina 更新的主题，其中说 Lilu 和 WhatGreen 应该先更新，所以我在旧的融合驱动器上的EFI中更新了两者，猜猜看，旧的卡塔利娜启动，（虽然USB不起作用）。
> > 无论如何我知道是什么导致了卡塔利娜问题，它应该是我关闭之前的更新！妈的。
> > 所以现在的情况：
> > 
> > 1. 我有一个没有 USB 设备的工作 Catalina。
> > 2. 您的 Big Sur EFI 无法启动机器。
> > 3. 另一个稍微改变USB配置的EFI可以启动机器，没有无线网络功能。
> >    2,3种情况说明你的EFI有问题。
> > 
> > > > 我从[https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/找到另一个](https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/%E6%89%BE%E5%88%B0%E5%8F%A6%E4%B8%80%E4%B8%AA)EFI [/](https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/)
> > > > 这个EFI使iTX机器启动到显示我4个选项的界面，最后一个是磁盘实用程序，但USB鼠标没有响应。我正在做。
> > > 
> > > 
> > > 修复了导致 XhciPortLimit 的 USB 问题。
> 
> 能不能分享一下邮箱[1172036926@qq.com](mailto:1172036926@qq.com)

中国人？

**Comment by 13372208606** [comment]
> > > 更新：
> > > 使用该 EFI 启动 Big Sur 后，蓝牙卡工作正常，但找不到 wifi，与 kexts 相关的更多。
> > > 而且，好消息是我发现了一些关于 Catalina 更新的主题，其中说 Lilu 和 WhatGreen 应该先更新，所以我在旧的更新驱动器上的EFI中更新了，猜猜看，旧的猜想利娜启动，（虽然是USB连接塔最终）。
> > > 三三我知道是什么了卡塔利娜问题，应该是我关闭之前的更新！妈的。
> > > 所以现在的情况：
> > > 
> > > 1. 我有一个没有 USB 设备的工作 Catalina。
> > > 2. 您的 Big Sur EFI 无法启动机器。
> > > 3. 另一个稍微改变USB配置的EFI可以启动机器，没有无线网络功能。
> > >    2,3种情况说明你的EFI有问题。
> > > 
> > > > > 我从[https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/找到另一个](https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/%E6%89%BE%E5%88%B0%E5%8F%A6%E4%B8%80%E4%B8%AA)EFI [/](https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/)
> > > > > 这个EFI使iTX机器启动到显示我4个选项的界面，最后一个是磁盘实用程序，但USB鼠标没有响应。我正在做。
> > > > 
> > > > 
> > > > 修复了导致 XhciPortLimit 的 USB 问题。
> > 
> > 
> > 能不能分享一下邮箱[1172036926@qq.com](mailto:1172036926@qq.com)
> 
> 中国人？

没有无线网络   要换网卡

**Comment by rishik44** [comment]
Hi guys, also have the same Z170N, I used the OP's EFI folder and everything works except for Bluetooth, any tips would be much appreciated!

**Comment by adrianzhang** [comment]
> > > 更新：
> > > 使用该 EFI 启动 Big Sur 后，蓝牙工作正常，但找不到 wifi 卡，与 kexts 相关的更多。
> > > 而且，好消息是我发现了一些关于 Catalina 更新的主题，其中说 Lilu 和 WhatGreen 应该先更新，所以我在旧的融合驱动器上的EFI中更新了两者，猜猜看，旧的卡塔利娜启动，（虽然USB不起作用）。
> > > 无论如何我知道是什么导致了卡塔利娜问题，它应该是我关闭之前的更新！妈的。
> > > 所以现在的情况：
> > > 
> > > 1. 我有一个没有 USB 设备的工作 Catalina。
> > > 2. 您的 Big Sur EFI 无法启动机器。
> > > 3. 另一个稍微改变USB配置的EFI可以启动机器，没有无线网络功能。
> > >    2,3种情况说明你的EFI有问题。
> > > 
> > > > > 我从[https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/找到另一个](https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/%E6%89%BE%E5%88%B0%E5%8F%A6%E4%B8%80%E4%B8%AA)EFI [/](https://www.tonymacx86.com/threads/big-sur-hd530-opencore-z170n-skylake.304138/)
> > > > > 这个EFI使iTX机器启动到显示我4个选项的界面，最后一个是磁盘实用程序，但USB鼠标没有响应。我正在做。
> > > > 
> > > > 
> > > > 修复了导致 XhciPortLimit 的 USB 问题。
> > 
> > 
> > 能不能分享一下邮箱[1172036926@qq.com](mailto:1172036926@qq.com)
> 
> 中国人？

我的机器还不能正常工作，你可以从我上面给出的链接中下载EFI。

**Comment by adrianzhang** [comment]
> Hi guys, also have the same Z170N, I used the OP's EFI folder and everything works except for Bluetooth, any tips would be much appreciated!

I researched wifi and bluetooth problem on the Internet and someone says bluetooth actually using USB bus, so you need to check if it can work with disable XhciPortLimit.

**Comment by wouterds** [comment]
Hi guys,

Bluetooth & wifi just work on my build. Note that I switched out the default network card with another one, see hardware list.

Cheers
Wouter

**Comment by adrianzhang** [comment]
> Hi guys, Bluetooth & wifi just work on my build. Note that I switched out the default network card with another one, see hardware list. Cheers Wouter
> […](#)
> Sent from my iPhone
> On 5 Jun 2021, at 14:34, Adrian Zhang ***@***.***> wrote: ﻿ Hi guys, also have the same Z170N, I used the OP's EFI folder and everything works except for Bluetooth, any tips would be much appreciated! I researched wifi and bluetooth problem on the Internet and someone says bluetooth actually using USB bus, so you need to check if it can work with disable XhciPortLimit. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Same wifi card (DW1560) used in my case.
And I bought another card which is a BCM943224PCIEBT2 to try. Wifi problem still exists until now. (PS: I am not using your EFI, another one I mentioned above instead.)

**Comment by rishik44** [comment]
Hi,

I have the same WiFi card (bcm9352) as you wouter. I’m still not
understanding why my Bluetooth is not working, it is very strange. Ok I
will try enabling the XHCI port limit.

Thanks

**Comment by rishik44** [comment]
> > Hi guys, also have the same Z170N, I used the OP's EFI folder and everything works except for Bluetooth, any tips would be much appreciated!
> 
> I researched wifi and bluetooth problem on the Internet and someone says bluetooth actually using USB bus, so you need to check if it can work with disable XhciPortLimit.

Ok thanks I will try enabling the limit again.

**Comment by rishik44** [comment]
> > > Hi guys, also have the same Z170N, I used the OP's EFI folder and everything works except for Bluetooth, any tips would be much appreciated!
> > 
> > 
> > I researched wifi and bluetooth problem on the Internet and someone says bluetooth actually using USB bus, so you need to check if it can work with disable XhciPortLimit.
> 
> Ok thanks I will try enabling the limit again.

Got it working! Had to rename the system config from MacPro6,1 to iMac17,1 and bluetooth is finally fully functional after a reboot!

**Comment by rishik44** [comment]
> Hi guys, Bluetooth & wifi just work on my build. Note that I switched out the default network card with another one, see hardware list. Cheers Wouter
> […](#)

Got it working! Had to rename the system config from MacPro6,1 to iMac17,1 and bluetooth is finally fully functional after a reboot!

Thanks Wouter
